import Head from "next/head"
import { useEffect, useState } from "react"
import generateFalseAnswers from "../utils/functions/generateFalseAnswers"
import generateQuizData from "../utils/functions/generateQuizData"
import getAllAnswers from "../utils/functions/getAllAnswers"

const Capitals = () => {
    const [quizData, setQuizData] = useState<any[]>([])
    const [capitals, setCapitals] = useState<string[]>([])

    useEffect(() => {
        fetch("https://restcountries.com/v3.1/all")
            .then(res => res.json())
            .then(data => {
                generateQuizData(data, setQuizData)
                getAllAnswers(data, "capital", "", setCapitals)
            })
    }, [])

    return (
        <div>
            <Head>
                <title>GeoQuix | Capitals</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <main>
                {quizData.map((c: any, idx: number) => {
                    const answers = generateFalseAnswers(c.capital, capitals)

                    return (
                        <div key={idx}>
                            <h1 className="text-3xl">{c.name.common}</h1>
                            <div className="flex gap-2">
                                {answers.map((a: string, idx) => {
                                    return <h2 className="border-2 py-2 px-4" key={idx}>{a}</h2>
                                })}
                            </div>
                        </div>
                    )
                })}
            </main>
        </div>
    )
}

export default Capitals