import Head from "next/head"
import Image from "next/image"
import { useEffect, useState } from "react"
import generateFalseAnswers from "../utils/functions/generateFalseAnswers"
import generateQuizData from "../utils/functions/generateQuizData"
import getAllAnswers from "../utils/functions/getAllAnswers"
import submitAnswer from "../utils/functions/submitAnswer"

const Flags = () => {
    const [quizData, setQuizData] = useState<any[]>([])
    const [flags, setFlags] = useState<string[]>([])
    const [score, setScore] = useState<number>(0)

    useEffect(() => {
        fetch("https://restcountries.com/v3.1/all")
            .then(res => res.json())
            .then(data => {
                generateQuizData(data, "flags", "png", setQuizData)
                getAllAnswers(data, "flags", "png", setFlags)
            })
    }, [])

    const answers = generateFalseAnswers(quizData[0]?.flags.png, flags)
    const quizLen = quizData.length

    return (
        <div>
            <Head>
                <title>GeoQuix | Flags</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center py-4 gap-4">
                <div className="flex flex-col gap-4 md:flex-row items-center">
                    <h2 className="text-2xl">What is the capital city?</h2>
                    <p className="border-2 py-4 px-8">{score} / 10</p>
                    <p>{quizLen} questions left</p>
                </div>

                {quizLen > 0 &&
                    <div className="flex flex-col items-center justify-center border-y-2 w-full py-6 px-8">
                        <h1 className="text-3xl">{quizData[0]?.name.common}</h1>
                        <div className="m-2"></div>
                        <div className="flex flex-col md:flex-row gap-2">
                            {answers.map((a: string, answerIdx: number) => {
                                return (
                                    <Image
                                        key={answerIdx}
                                        className="object-contain border-2 p-2 cursor-pointer hover:bg-gray-200"
                                        src={a}
                                        onClick={() => {
                                            submitAnswer(
                                                a,
                                                "flags",
                                                "png",
                                                quizData[0]?.flags.png,
                                                setScore,
                                                score,
                                                setQuizData,
                                                quizData
                                            )
                                        }}
                                        alt="Country Flag"
                                        width={150}
                                        height={100}
                                    />
                                )
                            })}
                        </div>
                    </div>}
               
            </main>
        </div>
    )
}

export default Flags
