import Head from "next/head"
import Image from "next/image"
import { useEffect, useState } from "react"
import QuizHeader from "../components/header/QuizHeader"
import FinishedModal from "../components/modals/FinishedModal"
import QuizStarter from "../components/quiz/QuizStarter"
import generateFalseAnswers from "../utils/functions/generateFalseAnswers"
import generateQuizData from "../utils/functions/generateQuizData"
import getAllAnswers from "../utils/functions/getAllAnswers"
import submitAnswer from "../utils/functions/submitAnswer"

const Flags = () => {
    const [quizData, setQuizData] = useState<any[]>([])
    const [flags, setFlags] = useState<string[]>([])
    const [score, setScore] = useState<number>(0)
    const [answered, setAnswered] = useState<number>(0)
    const [completed, setCompleted] = useState<boolean>(false)
    const [quizStart, setQuizStart] = useState<boolean>(false)

    useEffect(() => {
        fetch("https://restcountries.com/v3.1/all")
            .then(res => res.json())
            .then(data => {
                generateQuizData(data, "flags", "png", setQuizData)
                getAllAnswers(data, "flags", "png", setFlags)
            })
    }, [])

    const answers = generateFalseAnswers(quizData[0]?.flags.png, flags)
    const quizLen = quizData.length
    const category = "flag"

    return (
        <div>
            <Head>
                <title>GeoQuix | Flags</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center py-4 gap-4 relative">
                {!quizStart && <QuizStarter setQuizStart={setQuizStart} category={category} />}

                {quizStart && <div className="flex flex-col items-center py-4 gap-4 relative">

                    {completed &&
                        <FinishedModal
                            score={score}
                            answered={answered}
                            type="flags"
                        />
                    }

                    <QuizHeader
                        category={category}
                        score={score}
                        answered={answered}
                        setCompleted={setCompleted}
                    />

                    {quizLen > 0 &&
                        <div
                            style={completed ? {pointerEvents: "none"} : {pointerEvents: "auto"}}
                            className="flex flex-col items-center justify-center w-fit py-6 px-8 border-2 border-gray-700 rounded">
                            <h1 className="text-3xl">{quizData[0]?.name.common}</h1>
                            <div className="m-2"></div>
                            <div className="flex flex-col md:flex-row gap-2">
                                {answers.map((a: string, answerIdx: number) => {
                                    return (
                                        <Image
                                            key={answerIdx}
                                            className={`bg-inherit object-contain border-2 border-gray-700 rounded p-2 cursor-pointer 
                                            bg-gray-100 hover:bg-gray-700`}
                                            src={a}
                                            onClick={() => {
                                                submitAnswer(
                                                    a,
                                                    "flags",
                                                    "png",
                                                    quizData[0]?.flags.png,
                                                    setScore,
                                                    score,
                                                    setQuizData,
                                                    quizData,
                                                    setAnswered,
                                                    answered
                                                )
                                            }}
                                            alt="Country Flag"
                                            width={100}
                                            height={50}
                                        />
                                    )
                                })}
                            </div>
                        </div>}
                    </div>
                }
               
            </main>
        </div>
    )
}

export default Flags
