import Head from 'next/head'
import { Categories } from '../components/categories/Categories'

export default function Home() {

  return (
    <div>
      <Head>
        <title>GeoQuix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Categories />
      </main>
     
    </div>
  )
}
