import Head from 'next/head'
import { Categories } from '../components/categories/Categories'
import { Header } from '../components/header/Header'

export default function Home() {
  

  return (
    <div>
      <Head>
        <title>GeoQuix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Categories />
      </main>

      <footer>
        footer
      </footer>
    </div>
  )
}
