import Head from 'next/head'
import { Categories } from '../components/categories/Categories'
import { Footer } from '../components/footer/Footer'
import { Header } from '../components/header/Header'

export default function Home() {
  

  return (
    <div className='bg-gray-800 text-white h-screen relative'>
      <Head>
        <title>GeoQuix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Categories />
      </main>

      <footer className='absolute bottom-0'>
        <Footer />
      </footer>
    </div>
  )
}
