import Head from "next/head"
import { trpc } from "../utils/trpc"

const Leaderboard = () => {
    const allScores = trpc.getAllScores.useQuery().data

    return (
        <div>
            <Head>
                <title>GeoQuix | Leaderboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center py-4 gap-4 relative">
                {
                    allScores === undefined ? <p>Loading...</p> :
                        allScores.map((entry: any) => {
                            const {id, name, score, accuracy, quiz} = entry
                            return (
                                <div
                                    className="flex gap-4"
                                    key={id}>
                                    <p>{name}</p>
                                    <p>{score}</p>
                                    <p>{accuracy}</p>
                                    <p>{quiz}</p>
                                </div>
                            )
                        })
                }
            </main>

        </div>
    )
}

export default Leaderboard
