import Head from "next/head"
import { useEffect, useState } from "react"
import { Header } from "../components/header/Header"
import QuizHeader from "../components/header/QuizHeader"
import Quiz from "../components/quiz/Quiz"
import formatNumbers from "../utils/functions/formatNumbers"
import generateFalseAnswers from "../utils/functions/generateFalseAnswers"
import generateQuizData from "../utils/functions/generateQuizData"
import getAllAnswers from "../utils/functions/getAllAnswers"
import submitAnswer from "../utils/functions/submitAnswer"

const Population = () => {
    const [quizData, setQuizData] = useState<any[]>([])
    const [population, setPopulation] = useState<string[]>([])
    const [score, setScore] = useState<number>(0)

    useEffect(() => {
        fetch("https://restcountries.com/v3.1/all")
            .then(res => res.json())
            .then(data => {
                generateQuizData(data, "population", "", setQuizData)
                getAllAnswers(data, "population", "", setPopulation)
            })
    }, [])

    const answers = generateFalseAnswers(quizData[0]?.population, population)
    const quizLen = quizData.length

    return (
        <div>
            <Head>
                <title>GeoQuix | Population</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            
            <main className="flex flex-col items-center py-4 gap-4">
                <QuizHeader
                    category="population"
                    score={score}
                    quizLen={quizLen}
                />

                {quizLen > 0 &&
                    <Quiz
                        name={quizData[0]?.name.common}
                        type1="population"
                        answers={answers}
                        passedType={quizData[0]?.population}
                        setScore={setScore}
                        score={score}
                        setQuizData={setQuizData}
                        quizData={quizData}
                    />
                }
               
            </main>
        </div>
    )
}

export default Population