import Head from "next/head"
import { useEffect, useState } from "react"
import QuizHeader from "../components/header/QuizHeader"
import FinishedModal from "../components/modals/FinishedModal"
import Quiz from "../components/quiz/Quiz"
import QuizStarter from "../components/quiz/QuizStarter"
import generateFalseAnswers from "../utils/functions/generateFalseAnswers"
import generateQuizData from "../utils/functions/generateQuizData"
import getAllAnswers from "../utils/functions/getAllAnswers"

const Timezones = () => {
    const [quizData, setQuizData] = useState<any[]>([])
    const [timezones, setTimezones] = useState<string[]>([])
    const [score, setScore] = useState<number>(0)
    const [answered, setAnswered] = useState<number>(0)
    const [completed, setCompleted] = useState<boolean>(false)
    const [quizStart, setQuizStart] = useState<boolean>(false)

    useEffect(() => {
        fetch("https://restcountries.com/v3.1/all")
            .then(res => res.json())
            .then(data => {
                generateQuizData(data, "timezones", "", setQuizData)
                getAllAnswers(data, "timezones", "", setTimezones)
            })
    }, [])

    const answers = generateFalseAnswers(quizData[0]?.timezones, timezones)
    const quizLen = quizData.length
    const category = "timezone"

    return (
        <div>
            <Head>
                <title>GeoQuix | Timezones</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center py-4 gap-4 relative">
                {!quizStart && <QuizStarter setQuizStart={setQuizStart} category={category} />}

                {quizStart && <div className="flex flex-col items-center py-4 gap-4 relative">
                    {completed && <FinishedModal score={score} answered={answered} />}

                    <QuizHeader
                        category={category}
                        score={score}
                        answered={answered}
                        setCompleted={setCompleted}
                    />

                    {quizLen > 0 &&
                        <Quiz
                            name={quizData[0]?.name.common}
                            type1="timezones"
                            answers={answers}
                            passedType={quizData[0]?.timezones}
                            setScore={setScore}
                            score={score}
                            setQuizData={setQuizData}
                            quizData={quizData}
                            setAnswered={setAnswered}
                            answered={answered}
                            completed={completed}
                        />
                    }
                </div>
                }
               
            </main>
        </div>
    )
}

export default Timezones